# Generated by Django 4.0.3 on 2022-08-16 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_summary', models.CharField(max_length=300, verbose_name='Question Summary')),
                ('question_details', models.TextField(verbose_name='Question Details')),
                ('question_published', models.DateTimeField(auto_now_add=True, verbose_name='Question Published')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('question_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
